server:
  port: 9999

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/tmttstore
  mail:
    host: smtp.gmail.com
    port: 587
    username: alextrinh391@gmail.com
    password: srvumupkpwzlpcvw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

key_public: classpath:app.pub
key_private: classpath:app.key


