server:
  port: 9999

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/tmttstore
  mail:
    host: smtp.gmail.com
    port: 587
    username: alextrinh391@gmail.com
    password: srvumupkpwzlpcvw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud_name: duvnxrvqr
  api_key: 797378195252422
  api_secret: Urp4eOvXb46ePXEDntPXFSdDKgw

key_public: classpath:app.pub
key_private: classpath:app.key

open:
  api:
    title: API document
    version: v1.0.0
    description: Mota API document
    serverUrl: http://localhost:9999
    serverName: server test


jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

